name: Prettier Format
on: [push]
jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
        - name: Format Code
          uses: creyD/prettier_action@v4.3
          with:
            prettier_options: --write **/*
            only_changed: True